# Generated by Django 4.1.1 on 2022-09-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.systemitem'),
        ),
        migrations.AddField(
            model_name='systemitem',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemitem',
            name='type',
            field=models.CharField(choices=[('FILE', 'FILE'), ('FOLDER', 'FOLDER')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemitem',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
