# Generated by Django 4.1.1 on 2022-09-15 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemitem_parent_systemitem_size_systemitem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='api.systemitem'),
        ),
    ]
